name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    # Only trigger if changes are in the backend directory
    paths:
      - 'backend/app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/app/**'

jobs:
  build-and-deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    
    # Sets the default directory for all steps in this job
    defaults:
      run:
        working-directory: ./backend/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/app/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          # Sets the context for the Docker build
          context: ./backend/app
          push: true
          tags: shreyaspg21/fastchat-backend:${{ github.sha }}, shreyaspg21/fastchat-backend:latest

      - name: Set up Kubeconfig
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: azure/k8s-set-context@v4.0.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          kubectl set image deployment/fastchat-app-deployment \
            fastchat-backend=shreyaspg21/fastchat-backend:${{ github.sha }} \
            -n fastchat-ns